### ISSUE TITLE
QuantitativeUnit and unit

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/cheminfo-json-schema#6] opened 2021-04-28 05:33 UTC
We should discuss about how close we would like to adopt the specification of https://schema.org/QuantitativeValue

They called it unitText and not unit. 

For me like you did is ok.

**Comment by kjappelbaum** [comment] 2021-05-18 07:59
closing as duplicate of #12

**Closed by kjappelbaum** 2021-05-18 07:59 UTC
