### ISSUE TITLE
Storing value, minValue, maxValue

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/cheminfo-json-schema#7] opened 2021-04-28 05:35 UTC
In the current definition of a quantity we can also define a range using minValue and maxValue.

On one end I like this idea because those 2 values share the same unit.

On the other end I don't see how to deal with queries when the values may be in value, minValue or maxValue and I don't know how to convert to siValue. Should we decide that siValue is a 'private' value that would be the average between minValue and maxValue and would be the searchable field ?

https://github.com/cheminfo/cheminfo-json-schema/blob/main/ts/general/quantity.d.ts

**Comment by kjappelbaum** [comment] 2021-05-18 07:58
closing as duplicate of #22

**Closed by kjappelbaum** 2021-05-18 07:58 UTC
